<a href="https://colab.research.google.com/github/Ritesh-Gawande/Machine-Learning-Code/blob/main/SVM_on_DigitsDataset-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.datasets import load_digits
digit = load_digits()

In [3]:
digit.feature_names

['pixel_0_0',
 'pixel_0_1',
 'pixel_0_2',
 'pixel_0_3',
 'pixel_0_4',
 'pixel_0_5',
 'pixel_0_6',
 'pixel_0_7',
 'pixel_1_0',
 'pixel_1_1',
 'pixel_1_2',
 'pixel_1_3',
 'pixel_1_4',
 'pixel_1_5',
 'pixel_1_6',
 'pixel_1_7',
 'pixel_2_0',
 'pixel_2_1',
 'pixel_2_2',
 'pixel_2_3',
 'pixel_2_4',
 'pixel_2_5',
 'pixel_2_6',
 'pixel_2_7',
 'pixel_3_0',
 'pixel_3_1',
 'pixel_3_2',
 'pixel_3_3',
 'pixel_3_4',
 'pixel_3_5',
 'pixel_3_6',
 'pixel_3_7',
 'pixel_4_0',
 'pixel_4_1',
 'pixel_4_2',
 'pixel_4_3',
 'pixel_4_4',
 'pixel_4_5',
 'pixel_4_6',
 'pixel_4_7',
 'pixel_5_0',
 'pixel_5_1',
 'pixel_5_2',
 'pixel_5_3',
 'pixel_5_4',
 'pixel_5_5',
 'pixel_5_6',
 'pixel_5_7',
 'pixel_6_0',
 'pixel_6_1',
 'pixel_6_2',
 'pixel_6_3',
 'pixel_6_4',
 'pixel_6_5',
 'pixel_6_6',
 'pixel_6_7',
 'pixel_7_0',
 'pixel_7_1',
 'pixel_7_2',
 'pixel_7_3',
 'pixel_7_4',
 'pixel_7_5',
 'pixel_7_6',
 'pixel_7_7']

In [4]:
df = pd.DataFrame(digit.data, columns=digit.feature_names)
df.head()

   pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_5  pixel_7_6  pixel_7_7
0        0.0        0.0        5.0  ...        0.0        0.0        0.0
1        0.0        0.0        0.0  ...       10.0        0.0        0.0
2        0.0        0.0        0.0  ...       16.0        9.0        0.0
3        0.0        0.0        7.0  ...        9.0        0.0        0.0
4        0.0        0.0        0.0  ...        4.0        0.0        0.0

[5 rows x 64 columns]

In [5]:
df['target'] = digit.target
df.head()

   pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_6  pixel_7_7  target
0        0.0        0.0        5.0  ...        0.0        0.0       0
1        0.0        0.0        0.0  ...        0.0        0.0       1
2        0.0        0.0        0.0  ...        9.0        0.0       2
3        0.0        0.0        7.0  ...        0.0        0.0       3
4        0.0        0.0        0.0  ...        0.0        0.0       4

[5 rows x 65 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1797 entries, 0 to 1796
Data columns (total 65 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pixel_0_0  1797 non-null   float64
 1   pixel_0_1  1797 non-null   float64
 2   pixel_0_2  1797 non-null   float64
 3   pixel_0_3  1797 non-null   float64
 4   pixel_0_4  1797 non-null   float64
 5   pixel_0_5  1797 non-null   float64
 6   pixel_0_6  1797 non-null   float64
 7   pixel_0_7  1797 non-null   float64
 8   pixel_1_0  1797 non-null   float64
 9   pixel_1_1  1797 non-null   float64
 10  pixel_1_2  1797 non-null   float64
 11  pixel_1_3  1797 non-null   float64
 12  pixel_1_4  1797 non-null   float64
 13  pixel_1_5  1797 non-null   float64
 14  pixel_1_6  1797 non-null   float64
 15  pixel_1_7  1797 non-null   float64
 16  pixel_2_0  1797 non-null   float64
 17  pixel_2_1  1797 non-null   float64
 18  pixel_2_2  1797 non-null   float64
 19  pixel_2_3  1797 non-null   float64
 20  pixel_2_4  1797 non-null   float64
 21  pixel_2_5  1797 non-null   float64
 22  pixel_2_6  1797 non-null   float64
 23  pixel_2_7  1797 non-null   float64
 24  pixel_3_0  1797 non-null   float64
 25  pixel_3_1  1797 non-null   float64
 26  pixel_3_2  1797 non-null   float64
 27  pixel_3_3  1797 non-null   float64
 28  pixel_3_4  1797 non-null   float64
 29  pixel_3_5  1797 non-null   float64
 30  pixel_3_6  1797 non-null   float64
 31  pixel_3_7  1797 non-null   float64
 32  pixel_4_0  1797 non-null   float64
 33  pixel_4_1  1797 non-null   float64
 34  pixel_4_2  1797 non-null   float64
 35  pixel_4_3  1797 non-null   float64
 36  pixel_4_4  1797 non-null   float64
 37  pixel_4_5  1797 non-null   float64
 38  pixel_4_6  1797 non-null   float64
 39  pixel_4_7  1797 non-null   float64
 40  pixel_5_0  1797 non-null   float64
 41  pixel_5_1  1797 non-null   float64
 42  pixel_5_2  1797 non-null   float64
 43  pixel_5_3  1797 non-null   float64
 44  pixel_5_4  1797 non-null   float64
 45  pixel_5_5  1797 non-null   float64
 46  pixel_5_6  1797 non-null   float64
 47  pixel_5_7  1797 non-null   float64
 48  pixel_6_0  1797 non-null   float64
 49  pixel_6_1  1797 non-null   float64
 50  pixel_6_2  1797 non-null   float64
 51  pixel_6_3  1797 non-null   float64
 52  pixel_6_4  1797 non-null   float64
 53  pixel_6_5  1797 non-null   float64
 54  pixel_6_6  1797 non-null   float64
 55  pixel_6_7  1797 non-null   float64
 56  pixel_7_0  1797 non-null   float64
 57  pixel_7_1  1797 non-null   float64
 58  pixel_7_2  1797 non-null   float64
 59  pixel_7_3  1797 non-null   float64
 60  pixel_7_4  1797 non-null   float64
 61  pixel_7_5  1797 non-null   float64
 62  pixel_7_6  1797 non-null   float64
 63  pixel_7_7  1797 non-null   float64
 64  target     1797 non-null   int64
dtypes: float64(64), int64(1)
memory usage: 912.7 KB

In [7]:
digit.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
df[df.target==1].head()

    pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_6  pixel_7_7  target
1         0.0        0.0        0.0  ...        0.0        0.0       1
11        0.0        0.0        0.0  ...        1.0        0.0       1
21        0.0        0.0        0.0  ...        4.0        0.0       1
42        0.0        0.0        0.0  ...        0.0        0.0       1
47        0.0        0.0        0.0  ...        0.0        0.0       1

[5 rows x 65 columns]

In [9]:
df['Number'] = df.target.apply(lambda x: digit.target_names[x])
df.head()

   pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_7  target  Number
0        0.0        0.0        5.0  ...        0.0       0       0
1        0.0        0.0        0.0  ...        0.0       1       1
2        0.0        0.0        0.0  ...        0.0       2       2
3        0.0        0.0        7.0  ...        0.0       3       3
4        0.0        0.0        0.0  ...        0.0       4       4

[5 rows x 66 columns]

In [10]:
df.drop('Number',axis='columns',inplace=True)
df.head()

   pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_6  pixel_7_7  target
0        0.0        0.0        5.0  ...        0.0        0.0       0
1        0.0        0.0        0.0  ...        0.0        0.0       1
2        0.0        0.0        0.0  ...        9.0        0.0       2
3        0.0        0.0        7.0  ...        0.0        0.0       3
4        0.0        0.0        0.0  ...        0.0        0.0       4

[5 rows x 65 columns]

In [11]:
df

      pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_6  pixel_7_7  target
0           0.0        0.0        5.0  ...        0.0        0.0       0
1           0.0        0.0        0.0  ...        0.0        0.0       1
2           0.0        0.0        0.0  ...        9.0        0.0       2
3           0.0        0.0        7.0  ...        0.0        0.0       3
4           0.0        0.0        0.0  ...        0.0        0.0       4
...         ...        ...        ...  ...        ...        ...     ...
1792        0.0        0.0        4.0  ...        0.0        0.0       9
1793        0.0        0.0        6.0  ...        0.0        0.0       0
1794        0.0        0.0        1.0  ...        0.0        0.0       8
1795        0.0        0.0        2.0  ...        0.0        0.0       9
1796        0.0        0.0       10.0  ...        1.0        0.0       8

[1797 rows x 65 columns]

In [12]:
df0 = df[df.target==0]
df1 = df[df.target==1]
df2 = df[df.target==2]
df3 = df[df.target==3]
df4 = df[df.target==4]
df5 = df[df.target==5]
df6 = df[df.target==6]
df7 = df[df.target==7]
df8 = df[df.target==8]
df9 = df[df.target==9]

In [13]:
df1

      pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_6  pixel_7_7  target
1           0.0        0.0        0.0  ...        0.0        0.0       1
11          0.0        0.0        0.0  ...        1.0        0.0       1
21          0.0        0.0        0.0  ...        4.0        0.0       1
42          0.0        0.0        0.0  ...        0.0        0.0       1
47          0.0        0.0        0.0  ...        0.0        0.0       1
...         ...        ...        ...  ...        ...        ...     ...
1752        0.0        0.0        4.0  ...        0.0        0.0       1
1757        0.0        0.0        4.0  ...        0.0        0.0       1
1760        0.0        0.0        1.0  ...        0.0        0.0       1
1766        0.0        0.0        8.0  ...        0.0        0.0       1
1774        0.0        0.0        6.0  ...        0.0        0.0       1

[182 rows x 65 columns]

In [15]:
from matplotlib import pyplot as plt
%matplotlib inline

In [21]:
from sklearn.model_selection import train_test_split

In [23]:
df.columns

Index(['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4',
       'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1',
       'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6',
       'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3',
       'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0',
       'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5',
       'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2',
       'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7',
       'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4',
       'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', 'pixel_6_1',
       'pixel_6_2', 'pixel_6_3', 'pixel_6_4', 'pixel_6_5', 'pixel_6_6',
       'pixel_6_7', 'pixel_7_0', 'pixel_7_1', 'pixel_7_2', 'pixel_7_3',
       'pixel_7_4', 'pixel_7_5', 'pixel_7_6', 'pixel_7_7', 'target'],
      dtype='object')

In [24]:
x = df.drop(['target'],axis='columns')
y = df.target

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [26]:
len(x_train)

1437

In [27]:
len(x_test)

360

In [40]:
from sklearn.svm import SVC
model = SVC()

In [41]:
model.fit(x_train,y_train)

SVC()

In [42]:
model.score(x_test,y_test)

0.9916666666666667